### PR TITLE
Updated Readme file

### PR DESCRIPTION
**Pull request by AvinashMahanthi**
I had updated the readme file with table of contents and embedded code of conduct in it.

### CODE REVIEW

**Review by himanshusharma89 — CHANGES_REQUESTED** [review]
@AvinashMahanthi 
- In the table of contents, update the `Officially start the challenge`, don't add a link in it, just use the #officially-start-the-challenge. 
- Add a space before `See` in License.
- And why the last two lines removed and added?

**Comment by AvinashMahanthi** [comment]
> @AvinashMahanthi
> 
> * In the table of contents, update the `Officially start the challenge`, don't add a link in it, just use the #officially-start-the-challenge.
> * Add a space before `See` in License.
> * And why the last two lines removed and added?

1.For Officially start the challenge I had done that in previous commits, But it is not responding, you can see in the 3rd and 4th commits, If you can help I am happy with that.
2. I had added space before as per you.
3.I didn't get you here, which lines?

once the point 1 is resolved I will make a pull request @himanshusharma89 . please guide me there

**Comment by himanshusharma89** [comment]
@AvinashMahanthi Officially Start the Challenge is working without an issue, try it again. And the last two lines were deleted and added again.

**Comment by AvinashMahanthi** [comment]
@himanshusharma89 I had added the Officially Start the Challenge. and for the last two lines, I just added a new line so that it appeared in that way.  Please check and verify.

**Review by himanshusharma89 — APPROVED** [review]

**Comment by AvinashMahanthi** [comment]
@himanshusharma89 Could you please add the tag "Hacktoberfest-accepted"! for getting approved for hactoberfest

**Comment by himanshusharma89** [comment]
@AvinashMahanthi If the PR is merged, it is already included in Hacktoberfest:
`Submitted in a repo with the hacktoberfest topic AND (
    The PR is merged OR
    The PR has been approved
  )`

**Comment by himanshusharma89** [comment]
@all-contributors please add @HeyKos for doc

**Comment by himanshusharma89** [comment]
@all-contributors please add @AvinashMahanthi for doc

**Pull request merged**
