### PR TITLE
Add FAQs page

### PR DESCRIPTION
**Pull request by HeyKos**
I've addressed issue #21 with the changes in this pull request. Per @himanshusharma89's request I've used `PageView` to achieve navigating to the FAQs content. I've locked the gesture switching on the `PageView` and instead require tapping on menu items to jump between pages. This requires `VoidCallback` parameters to be passed to the `BottomBar` and `TopBar` widgets, so that the logic to jump between pages can be provided by the `Dashboard` widget. 

I've tested these changes in Chrome across small, medium, and large displays to ensure the functionality works, and the content is displayed properly in al scenarios.

### CODE REVIEW

**Comment by himanshusharma89** [comment]
Perfect! @HeyKos, can you attach all the screenshots.

**Comment by HeyKos** [comment]
Attached screenshots of desktop and mobile views of the FAQs page.

Screen Shot 2020-10-11 at 8 59 42 AM
Screen Shot 2020-10-11 at 9 00 09 AM

**Review by himanshusharma89 — CHANGES_REQUESTED** [review]
@HeyKos Can you add these things:
- In the get mobileBody Widget, wrap the PageView within the Stack and set the Align widget in children(below pageview). The PageView will contain the ListView and FAQs.
- Remove the BottomBar and Stack from the faqs.dart
- Use animateToPage instead of jumpToPage for better web-experience in the dashboard.dart
- Update the scrollDirection to horizontal for desktopBody widget.
- Add a scrollbar in the faq list, and make `isAlwaysShown` true
- Remove the new keyword because calling a class will always return a new instance of that class

**Comment by HeyKos** [comment]
@himanshusharma89 I've made all the requested revisions. I really liked the suggestion to move the `BottomBar` to the `mobileBody` widget. It certainly make implementing additional pages much easier in the future. Thanks for reviewing. I've uploaded 2 gifs to demonstrate the mobile and desktop experiences.
FAQsDesktop
FAQsMobile

**Comment by himanshusharma89** [comment]
Perfect!

**Comment by himanshusharma89** [comment]
@all-contributors please add @HeyKos for code

**Pull request merged**
